services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile.srv
      target: dev
    working_dir: /var/www/html/members
    ports:
      - "10100:10100"    #this line maps your pc port to the container port
      - "10300:10300"    # bank mock server UI and API
      - "10301:10301"    # reserved for a second mock server
    depends_on:
      - db    #this line links this container to the db container
    environment:
      BANK_MOCK_DB_HOST: db
      BANK_MOCK_DB_PORT: 3306
      BANK_MOCK_DB_USER: root
      BANK_MOCK_DB_PASSWORD: dev4password
      BANK_MOCK_DB_NAME: rb_mock
      BANK_MOCK_PORT: 10300
    volumes:
      - ./:/var/www/html/members    #this line maps the content of ./html in your pc to the /var/www/html of the container
      # override configuration, modifiable in original place only
      - ./docker/config/dev/_cfg.php:/var/www/html/members/cfg/_cfg.php:ro
      - ./docker/config/dev/_globals.php:/var/www/html/members/cfg/_globals.php:ro
      - ./docker/config/dev/_tables.php:/var/www/html/members/cfg/_tables.php:ro
  db:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: dev4password
      MARIADB_DATABASE: members_dev
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppass
    volumes:
      # persistent database storage
      - ./db_data/dev:/var/lib/mysql    #this line maps the content of ./db_data/dev in your pc to the /var/lib/mysql of the container
      # initial database content
      - ./docker/db_init/d235220_members_latest.sql:/docker-entrypoint-initdb.d/d235220_members.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "10101:80"    #this line maps your pc port to the container port
    depends_on:
      - db    #this line links this container to the db container
    environment:
      PMA_HOST: db
