const POPULATED_PAYMENT_RULES = [
  {
    sport: 'ob',
    eventType: 'Z',
    financeType: '7',
    rankings: ['1', '4'],
    paymentType: 'C',
    amount: '99',
    chargedItems: [],
  },
  {
    sport: 'ob',
    eventType: 'Z',
    financeType: '8',
    rankings: ['1', '4'],
    paymentType: 'C',
    amount: '98',
    chargedItems: [],
  },
  {
    sport: 'ob',
    eventType: 'Z',
    financeType: '6',
    rankings: ['1', '4'],
    paymentType: 'C',
    amount: '97',
    chargedItems: [],
  },
  {
    sport: 'ob',
    eventType: 'Z',
    financeType: '2',
    rankings: ['1', '4'],
    paymentType: 'C',
    amount: '96',
    chargedItems: [],
  },
  {
    sport: 'ob',
    eventType: 'Z',
    financeType: '1',
    rankings: ['1', '4'],
    paymentType: 'C',
    amount: '95',
    chargedItems: [],
  },
  {
    sport: 'ob',
    eventType: 'Z',
    financeTypes: [],
    terms: ['2', '3', '4', '5'],
    paymentType: 'R',
    amount: '101',
    chargedItems: ['1'],
  },
  {
    sports: [],
    eventTypes: [],
    financeType: '1',
    paymentType: 'C',
    amount: '93',
    chargedItems: [],
  },
  {
    sports: [],
    eventType: 'V',
    financeType: '9',
    paymentType: 'C',
    amount: '91',
    chargedItems: [],
  },
  {
    sports: [],
    eventType: 'V',
    financeType: '8',
    paymentType: 'C',
    amount: '90',
    chargedItems: [],
  },
  {
    sports: [],
    eventType: 'V',
    financeType: '7',
    paymentType: 'C',
    amount: '89',
    chargedItems: [],
  },
  {
    sports: [],
    eventType: 'V',
    financeType: '3',
    paymentType: 'C',
    amount: '88',
    chargedItems: [],
  },
  {
    sport: 'ob',
    eventType: 'Z',
    financeType: '3',
    rankings: ['1', '2', '4'],
    paymentType: 'C',
    amount: '87',
    chargedItems: [],
  },
  {
    sports: [],
    eventType: 'V',
    financeType: '2',
    paymentType: 'C',
    amount: '86',
    chargedItems: [],
  },
  {
    sports: [],
    eventType: 'J',
    financeTypes: [],
    paymentType: 'C',
    amount: '85',
    chargedItems: [],
  },
  {
    sports: [],
    eventType: 'N',
    financeTypes: [],
    paymentType: 'C',
    amount: '84',
    chargedItems: [],
  },
  {
    sports: [],
    eventType: 'V',
    financeType: '1',
    paymentType: 'C',
    amount: '83',
    chargedItems: [],
  },
  {
    sport: 'ob',
    eventType: 'Z',
    financeType: '7',
    rankings: ['1', '2', '4'],
    paymentType: 'C',
    amount: '82',
    chargedItems: [],
  },
  {
    sport: 'mtbo',
    eventTypes: [],
    financeTypes: [],
    paymentType: 'C',
    amount: '81',
    chargedItems: [],
  },
  {
    sport: 'lob',
    eventTypes: [],
    financeTypes: [],
    paymentType: 'C',
    amount: '80',
    chargedItems: [],
  },
  {
    sport: 'jine',
    eventTypes: [],
    financeTypes: [],
    paymentType: 'C',
    amount: '79',
    chargedItems: [],
  },
  {
    sports: [],
    eventType: 'S',
    financeTypes: [],
    paymentType: 'C',
    amount: '78',
    chargedItems: [],
  },
  {
    financeType: '1',
    eventType: 'T',
    paymentType: 'P',
    amount: '45',
    chargedItems: '1',
  },
  {
    financeType: '1',
    eventType: 'T',
    paymentType: 'P',
    amount: '100',
    chargedItems: '2',
  },
  {
    sport: 'ob',
    eventType: 'Z',
    financeType: '2',
    rankings: ['1', '2', '4'],
    paymentType: 'C',
    amount: '76',
    chargedItems: [],
  },
  {
    sport: 'ob',
    eventType: 'Z',
    financeType: '1',
    rankings: ['1', '2', '4'],
    paymentType: 'C',
    amount: '75',
    chargedItems: [],
  },
  {
    sport: 'trail',
    eventTypes: [],
    financeTypes: [],
    paymentType: 'C',
    amount: '74',
    chargedItems: [],
  },
];

module.exports = {
  POPULATED_PAYMENT_RULES,
};
